# Generated by Django 5.1.1 on 2024-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(choices=[('1st', '1st Term'), ('2nd', '2nd Term')], max_length=100),
        ),
    ]
