# Generated by Django 5.1.1 on 2024-11-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0002_alter_term_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='term',
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic_calendar.academicyear'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
