# Generated by Django 5.1.1 on 2024-11-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
