# Generated by Django 5.1.4 on 2024-12-16 14:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
