# Generated by Django 5.1.1 on 2024-11-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_new', '0004_slider_club'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
